-- MySQL Script generated by MySQL Workbench
-- 04/26/15 22:38:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema artists
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema artists
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `artists` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `artists` ;

-- -----------------------------------------------------
-- Table `artists`.`artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artists`.`artists` (
  `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NULL,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artists`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artists`.`albums` (
  `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `year` INT NULL,
  `artist_id` INT NOT NULL,
  INDEX `fk_albums_artists1_idx` (`artist_id` ASC),
  CONSTRAINT `fk_albums_artists1`
    FOREIGN KEY (`artist_id`)
    REFERENCES `artists`.`artists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artists`.`songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artists`.`songs` (
  `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `duration` VARCHAR(45) NULL,
  `album_id` INT NOT NULL,
  INDEX `fk_songs_albums_idx` (`album_id` ASC),
  CONSTRAINT `fk_songs_albums`
    FOREIGN KEY (`album_id`)
    REFERENCES `artists`.`albums` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artists`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artists`.`users` (
  `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
